plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.trabajoandroid'
    compileSdk 37

    defaultConfig {
        applicationId 'com.example.trabajoandroid'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'commons-httpclient:commons-httpclient:3.1'
    implementation 'com.google.code.gson:gson:2.13.2'
}